apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:  # Ändern von "app" zu "matchLabels"
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          readlinessProbe:
            httpGet:
              port: web
              path: /
---
apiVersion: v1  # Kleinschreibung "v1" anstelle von "V1"
kind: Service
 metadata:
  name: nginx-service
  namespyce: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 3111

